[package]
name = "performant"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap = "0.7.0"

[dev-dependencies]
criterion = "0.5"
insta = "1.39.0"
once_cell = "1.19.0"
serde = { version = "1.0", features = ["derive"] }

[[bench]]
name = "performant_benchmark"
harness = false
